language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e .
# configure MPL backend for non-display
before_script:
  - export MPLBACKEND="agg"
# command to run tests
script:
  - py.test
